# тип конфигурации
env: "local" # local, dev, prod
# путь к базе данных
storage_path: "./storage/storage.db"
# параметры http сервера
http_server:
  # адрес, на котором будет запущено приложение
  address: "localhost:8082"
  # время обработки одного запроса (начиная с получения и заканчивая ответом)
  timeout: 4s
  # максимальное время между запросами клиента
  idle_timeout: 60s
  # время, за которое должен завершиться graceful shutdown
  graceful_shutdown_timeout: 10s
  # имя пользователя, который сможет сохранять ссылки
  user: "fatalistix"
  # пароль будет доставаться из переменной окружения
service:
  # длина псевдонима для ссылки
  alias_length: 10
